version: '2'

services:
  api:
    image: 'portfolio2-showtime:latest'
    build:
      context: .
    ports:
      - '8080:8080'
    container_name: api
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres